# Generated by Django 3.2.6 on 2021-08-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, null=True),
        ),
        migrations.AddField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
