# Generated by Django 3.2.6 on 2021-08-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210819_1006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='function',
            options={'verbose_name': 'функцию', 'verbose_name_plural': 'функции'},
        ),
        migrations.AlterField(
            model_name='function',
            name='creation_date',
            field=models.DateTimeField(auto_created=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='function',
            name='dt',
            field=models.IntegerField(verbose_name='Шаг t, часы'),
        ),
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='График'),
        ),
        migrations.AlterField(
            model_name='function',
            name='interval',
            field=models.IntegerField(verbose_name='Интервал t, дней'),
        ),
        migrations.AlterField(
            model_name='function',
            name='statement',
            field=models.CharField(max_length=128, verbose_name='Выражение'),
        ),
    ]
