# Generated by Django 3.2.6 on 2021-08-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210819_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обработки'),
        ),
        migrations.AlterField(
            model_name='function',
            name='statement',
            field=models.CharField(max_length=128, verbose_name='Функция'),
        ),
    ]
