# Generated by Django 3.2.6 on 2021-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210819_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
