# Generated by Django 3.2.6 on 2021-08-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_function_graph'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='graph',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='График'),
        ),
    ]
